version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.0.0"

jobs:
  build-ios:
    executor: macos-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-deps-v1-{{ checksum "package-lock.json" }}
            - node-deps-v1-

      - run:
          name: Install Node.js with nvm
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            node -v
            npm install -g yarn

      - save_cache:
          paths:
            - node_modules
          key: node-deps-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install pod dependencies
          command: |
            cd ios
            pod install

      - run:
          name: Build iOS app
          command: |
            xcodebuild -workspace ios/MyApp.xcworkspace \
                       -scheme MyApp \
                       -sdk iphoneos \
                       -configuration Release \
                       archive -archivePath $CIRCLE_WORKING_DIRECTORY/build/MyApp.xcarchive

      - run:
          name: Export .ipa
          command: |
            xcodebuild -exportArchive \
                       -archivePath $CIRCLE_WORKING_DIRECTORY/build/MyApp.xcarchive \
                       -exportOptionsPlist ios/exportOptions.plist \
                       -exportPath $CIRCLE_WORKING_DIRECTORY/build/

      - store_artifacts:
          path: build/
          destination: /artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-ios
