version: 2.1

executors:
  react_native_executor:
    docker:
      - image: circleci/node:18
    working_directory: ~/project

jobs:
  setup:
    executor: react_native_executor
    steps:
      - checkout
      - run:
          name: Install NVM and Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            echo "export NVM_DIR=$NVM_DIR" >> $BASH_ENV
            echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV

      - run:
          name: Verify Node.js and Yarn
          command: |
            source $BASH_ENV
            node -v
            yarn -v

      - restore_cache:
          keys:
            - node-deps-{{ checksum "yarn.lock" }}
            - node-deps-

      - run:
          name: Install dependencies
          command: |
            source $BASH_ENV
            yarn install --frozen-lockfile

      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  ios_build:
    macos:
      xcode: 14.2.0
    working_directory: ~/project
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-deps-{{ checksum "yarn.lock" }}
            - node-deps-

      - run:
          name: Install CocoaPods
          command: |
            cd ios
            pod install

      - run:
          name: Build iOS
          command: |
            xcodebuild -workspace ios/MyApp.xcworkspace \
              -scheme MyApp \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
              build

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - ios_build:
          requires:
            - setup
