version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.0.0"  # Chọn phiên bản Xcode (Xcode 14.0 trở lên)

jobs:
  build-ios:
    executor: macos-executor
    steps:
      - checkout

      - run:
          name: Install Node.js và Yarn
          command: |
            brew install node
            npm install -g yarn

      - run:
          name: Cài đặt pod dependencies
          command: |
            cd ios
            pod install

      - run:
          name: Build iOS app
          command: |
            xcodebuild -workspace ios/MyApp.xcworkspace \
                       -scheme MyApp \
                       -sdk iphoneos \
                       -configuration Release \
                       archive -archivePath $CIRCLE_WORKING_DIRECTORY/build/MyApp.xcarchive

      - run:
          name: Export .ipa
          command: |
            xcodebuild -exportArchive \
                       -archivePath $CIRCLE_WORKING_DIRECTORY/build/MyApp.xcarchive \
                       -exportOptionsPlist ios/exportOptions.plist \
                       -exportPath $CIRCLE_WORKING_DIRECTORY/build/

      - store_artifacts:
          path: build/
          destination: /artifacts
