version: 2.1

executors:
  macos-executor:
    macos:
      xcode: "14.0.0"  # Xcode version phù hợp (tuỳ chỉnh theo dự án)

jobs:
  build:
    executor: macos-executor
    steps:
      - checkout  # Lấy mã nguồn mới nhất

      # Cài đặt Node.js và Yarn
      - run:
          name: Install Node.js with nvm
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            node -v
            npm install -g yarn

      # Kiểm tra node và yarn
      - run:
          name: Verify Node.js and Yarn
          command: |
            node -v
            yarn -v

      # Cài dependencies
      - run:
          name: Install dependencies
          command: yarn install

      # Cài đặt CocoaPods (iOS)
      - run:
          name: Install pod dependencies
          command: |
            cd ios
            pod install

      # Build app iOS bằng xcodebuild
      - run:
          name: Build iOS App
          command: |
            xcodebuild -workspace ios/MyApp.xcworkspace \
                       -scheme MyApp \
                       -sdk iphoneos \
                       -configuration Release \
                       archive -archivePath $PWD/build/MyApp.xcarchive

      # Xuất file IPA để cài lên thiết bị
      - run:
          name: Export .ipa
          command: |
            xcodebuild -exportArchive \
                       -archivePath $PWD/build/MyApp.xcarchive \
                       -exportOptionsPlist ios/exportOptions.plist \
                       -exportPath $PWD/build

      # Upload IPA lên CircleCI artifacts
      - store_artifacts:
          path: build/*.ipa
          destination: MyApp.ipa

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
