name: Build iOS App

on: 
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Install CocoaPods
        run: pod install --project-directory=ios

      - name: Build iOS App
        run: xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -sdk iphoneos -configuration Release archive -archivePath ${{ github.workspace }}/YourApp.xcarchive

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/YourApp.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath ${{ github.workspace }}/build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: ${{ github.workspace }}/build
